# fly.toml app configuration file generated for lobbymanager on 2023-06-06T10:49:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lobbymanager"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8000"
  APP_ENV = "prod"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
